### ISSUE TITLE
About gdal

### ISSUE THREAD

**Issue by ricardoCyy** [zhuang-hao-ming/make-taz#1]
Why you don't want to import gdal in this project? Is there anything about LICENSE? Or about performance?
btw, great work! :)

**Comment by ricardoCyy** [comment]
If you want to avoid the unfriendly installation of GDAL, then switch to "rasterio" doesn't change anything. It still [Requires gdal](https://www.lfd.uci.edu/~gohlke/pythonlibs/)(search "**rasterio**" in this website).

**Comment by zhuang-hao-ming** [comment]
thank you for your suggestions. I just don't want to directly use GDAL as it's low level API.

**Comment by ricardoCyy** [comment]
> thank you for your suggestions. I just don't want to directly use GDAL as it's low level API.

Thx for your reply.
For “**low level**” you mean its bad performance or its bad design? This may be a stupid opinion but I found it hard to avoid **GDAL** or any **osgeo** module if I want to apply any GIS operation in python.
For example, I want to convert shp file to tiff in wgs84 crs, and I found **GDAL** is the most recommended module to make it happens. Do you have any advise about any alternative that could replace **GDAL**?

**Comment by zhuang-hao-ming** [comment]
When I say low level, I mean GDAL is a low-level implementation similar to C language [https://en.wikipedia.org/wiki/Low-level_programming_language](url).
I prefer to use more abstract python packages.
`Rasterio` package encapsulates `GDAL` grid operation well, Fiona encapsulates `osgeo` vector operation well, `Geopandas` is also a good package to further encapsulate `Fiona.`
Although all operations are based on GDAL, I prefer not to use GDAL directly.
By the way, `Rasterio` can convert shp into raster.

**Comment by ricardoCyy** [comment]
Great!
It does annoy me to use a low-level api like GDAL. I'm trying Rasterio and Fiona to achieve my goals!
Thx for your explicit suggestions.
