### ISSUE TITLE
请问您是如何获取相关城市的tif数据的？

### ISSUE THREAD

**Issue by Dreamzz5** [zhuang-hao-ming/make-taz#2]
在获取tif数据后怎么得到每个区域的 boundaries对应的经纬度呢？

**Comment by zhuang-hao-ming** [comment]
不好意思，没有看懂你的问题，你可以问的清楚一点吗？

**Comment by Dreamzz5** [comment]
我看您的demo里的是深圳的tif格式路网数据，想问问如何获取其他城市的，比如，成都，北京之类的tif数据。

**Comment by zhuang-hao-ming** [comment]
你可以下载免费的矢量路网数据（如osm）然后使用arcgis软件转成tif格式，分辨率建议高一些，如5m

**Comment by Dreamzz5** [comment]
了解了，感谢！
